
default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: van.minh
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  host: localhost

test:
  <<: *default
  host: localhost


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
